// Re-export shared types for use in electron main process (type-only; no runtime dependency on src)
export type {
  ServerId,
  PluginType,
  BuildTarget,
  GeneratorVersionKey,
  RegionKind,
  DiscoverMethod,
  RewardRecipeId,
  ServerProfile,
  DiscordSrvSettings,
  ImportedSource,
  RegionRecord,
  OnboardingConfig,
  ServerSummary,
  ServerSummaryWithStats,
  ImportResult,
  BuildResult,
  BuildReport,
  BuildListItem,
  PluginFolderCompareStatus,
  PluginFolderCompareFileResult,
  PluginFolderCompareResult,
  PluginFolderCompareResponse,
  ComparePreset,
  ComparePresetMutationResult,
  ComparePresetDeleteResult,
  DropTableItemOverride,
  DropTableDefinition,
  DropTablesConfig,
  DropTableCatalogSummary,
} from '@shared/types'

export const PLUGIN_TYPES: import('@shared/types').PluginType[] = ['aa', 'ce', 'tab', 'lm', 'lmcd', 'mc', 'cw']
